version: '3'

services:
  nutab:
    build:
      context: .
      args:
        - DATABASE_URL=${DATABASE_URL}
    restart: always
    ports:
      - "3000:3000"
    environment:
      # Use the variable from the local .env file
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - /volume1/Documents/NuTab/public/uploads:/app/uploads